const RouteView = "RouteView";
module.exports = {
  path: "/admin/vpx",
  name: "vpx",
  hidden: false,
  meta: { title: "VPX管理", permission: ["superadmin"] },
  component: RouteView,
  children: [
    {
      path: "/admin/vpx/nsip",
      name: "nsip",
      component: `() => import('@/views/admin/ddc/dir')`,
      meta: { title: "NSIP、SNIP配置", permission: ["superadmin"] },
    },
    {
      path: "/admin/vpx/auth",
      name: "auth",
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: { title: "身份认证", permission: ["superadmin"] },
    },
    {
      path: "/admin/vpx/route",
      name: "route",
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: { title: "路由管理", permission: ["superadmin"] },
    },
    {
      path: "/admin/vpx/certificate",
      name: "certificate",
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: { title: "服务器证书", permission: ["superadmin"] },
    },
    {
      path: "/admin/vpx/system",
      name: "system",
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: { title: "系统配置管理", permission: ["superadmin"] },
    },
    {
      path: "/admin/vpx/them",
      name: "them",
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: { title: "主题配置", permission: ["superadmin"] },
    },
    {
      path: "/admin/vpx/secure",
      name: "secure",
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: { title: "安全接入策略管理", permission: ["superadmin"] },
    },
    {
      path: "/admin/vpx/snip_edit",
      name: "snip_edit",
      hidden: true,
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: {
        title: "编辑SNIP",
        permission: ["superadmin"],
        parentName: "nsip",
      },
    },
    {
      path: "/admin/vpx/nsip_edit",
      name: "nsip_edit",
      hidden: true,
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: {
        title: "编辑NSIP",
        permission: ["superadmin"],
        parentName: "nsip",
      },
    },
    {
      path: "/admin/vpx/host_edit",
      name: "host_edit",
      hidden: true,
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: {
        title: "编辑主机名等",
        permission: ["superadmin"],
        parentName: "nsip",
      },
    },
    {
      path: "/admin/vpx/server_add",
      name: "server_add",
      hidden: true,
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: {
        title: "新增身份认证服务器",
        permission: ["superadmin"],
        parentName: "auth",
      },
    },
    {
      path: "/admin/vpx/server_edit",
      name: "server_edit",
      hidden: true,
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: {
        title: "编辑身份认证服务器",
        permission: ["superadmin"],
        parentName: "auth",
      },
    },
    {
      path: "/admin/vpx/route_create",
      name: "route_create",
      hidden: true,
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: {
        title: "新增路由",
        permission: ["superadmin"],
        parentName: "route",
      },
    },
    {
      path: "/admin/vpx/route_edit",
      name: "route_edit",
      hidden: true,
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: {
        title: "编辑路由",
        permission: ["superadmin"],
        parentName: "route",
      },
    },
    {
      path: "/admin/vpx/certificate_create",
      name: "certificate_create",
      hidden: true,
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: {
        title: "安装服务器证书",
        permission: ["superadmin"],
        parentName: "certificate",
      },
    },
    {
      path: "/admin/vpx/certificate_edit",
      name: "certificate_edit",
      hidden: true,
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: {
        title: "更新服务器证书",
        permission: ["superadmin"],
        parentName: "certificate",
      },
    },
    {
      path: "/admin/vpx/certificate_detail",
      name: "certificate_detail",
      hidden: true,
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: {
        title: "证书详情",
        permission: ["superadmin"],
        parentName: "certificate",
      },
    },
    {
      path: "/admin/vpx/config_edit",
      name: "config_edit",
      hidden: true,
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: {
        title: "编辑配置",
        permission: ["superadmin"],
        parentName: "system",
      },
    },
    {
      path: "/admin/vpx/theme_create",
      name: "theme_create",
      hidden: true,
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: {
        title: "新增主题",
        permission: ["superadmin"],
        parentName: "them",
      },
    },
    {
      path: "/admin/vpx/theme_edit",
      name: "theme_edit",
      hidden: true,
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: {
        title: "编辑主题",
        permission: ["superadmin"],
        parentName: "them",
      },
    },
    {
      path: "/admin/vpx/dist_create",
      name: "dist_create",
      hidden: true,
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: {
        title: "新增策略",
        permission: ["superadmin"],
        parentName: "secure",
      },
    },
    {
      path: "/admin/vpx/dist_edit",
      name: "dist_edit",
      hidden: true,
      component: `() => import("@/views/admin/ddc/dir")`,
      meta: {
        title: "编辑策略",
        permission: ["superadmin"],
        parentName: "secure",
      },
    },
  ],
};
